### ISSUE TITLE
About install pathman-sr problem

### ISSUE THREAD

**Issue by johnny9667** [CiscoDevNet/pathman-sr#6]
I Step by step install  
In the "bower install" show error

```
root@ww:/home/ww/下載/pathman-sr-master/client-src/pathman_sr# bower install
[{
  "code": "ESUDO",
  "details": "Since bower is a user command, there is no need to execute it with superuser permissions.\nIf you're having permission errors when using bower without sudo, please spend a few minutes learning more about how your system should work and make any necessary repairs.\n\nhttp://www.joyent.com/blog/installing-node-and-npm\nhttps://gist.github.com/isaacs/579814\n\nYou can however run a command with sudo using --allow-root option",
  "id": "ESUDO",
  "level": "error",
  "data": {},
  "message": "Cannot be run with sudo",
  "stacktrace": "Error: Cannot be run with sudo\n    at createError (/usr/lib/node_modules/bower/lib/util/createError.js:4:15)\n    at rootCheck (/usr/lib/node_modules/bower/lib/util/rootCheck.js:26:24)\n    at Object.<anonymous> (/usr/lib/node_modules/bower/lib/bin/bower.js:33:1)\n    at Module._compile (module.js:570:32)\n    at Object.Module._extensions..js (module.js:579:10)\n    at Module.load (module.js:487:32)\n    at tryModuleLoad (module.js:446:12)\n    at Function.Module._load (module.js:438:3)\n    at Module.require (module.js:497:17)\n    at require (internal/module.js:20:19)"
}]

```
​in the "bower install --allow-root option" show error

```
root@ww:/home/ww/下載/pathman-sr-master/client-src/pathman_sr# bower install  --allow-root option
[{
  "code": "ENOGIT",
  "data": {
    "endpoint": {
      "name": "angular",
      "source": "angular",
      "target": "~1.5.0"
    }
  },
  "id": "ENOGIT",
  "level": "error",
  "message": "git is not installed or not in the PATH",
  "stacktrace": "Error: git is not installed or not in the PATH\n    at createError (/usr/lib/node_modules/bower/lib/util/createError.js:4:15)\n    at GitHubResolver.GitResolver (/usr/lib/node_modules/bower/lib/core/resolvers/GitResolver.js:45:15)\n    at GitHubResolver.GitRemoteResolver (/usr/lib/node_modules/bower/lib/core/resolvers/GitRemoteResolver.js:10:17)\n    at new GitHubResolver (/usr/lib/node_modules/bower/lib/core/resolvers/GitHubResolver.js:13:23)\n    at /usr/lib/node_modules/bower/lib/core/resolverFactory.js:18:16\n    at /usr/lib/node_modules/bower/lib/node_modules/q/q.js:1229:26\n    at _fulfilled (/usr/lib/node_modules/bower/lib/node_modules/q/q.js:834:54)\n    at self.promiseDispatch.done (/usr/lib/node_modules/bower/lib/node_modules/q/q.js:863:30)\n    at Promise.promise.promiseDispatch (/usr/lib/node_modules/bower/lib/node_modules/q/q.js:796:13)\n    at /usr/lib/node_modules/bower/lib/node_modules/q/q.js:556:49"
}]

```

**Comment by nikmon2** [comment]
To get pathman_sr running, you don't need to re-build, instead you can use the setup as is.
- Take a look at: https://github.com/CiscoDevNet/pathman-sr/tree/master/dCloud

Let me know if that works for you?

**Comment by zverevalexei** [comment]
Hi @johny9667

I agree with Niklas. I would also add that the command that you used is only required to run, when you add new functionality to Pathman SR. If you are just playing with app, you don't need to work with code under /client-src/ directory. Instead, the catalog /client/ contains pre-built environment for you to run Pathman SR application.

If you need more comments or help, please let us know.

Alex

**Comment by zverevalexei** [comment]
Closed as resolved.
If any further assistance is required - reopen the issue.
